"""add filepath fields

Revision ID: 681e591e93b1
Revises: 772a9961da32
Create Date: 2026-06-26 00:05:52.398850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '681e591e93b1'
down_revision: Union[str, None] = '772a9961da32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_tasks', sa.Column('file_path', sa.Text(), nullable=True))
    op.alter_column('completed_tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('completed_tasks', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('failed_tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('failed_tasks', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('tasks', sa.Column('file_path', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('task_metadata', sa.JSON(), nullable=True))
    op.alter_column('tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('tasks', 'task_metadata')
    op.drop_column('tasks', 'file_path')
    op.alter_column('failed_tasks', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('failed_tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('completed_tasks', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('completed_tasks', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('completed_tasks', 'file_path')
    # ### end Alembic commands ###
