"""Add failed task and some additional fields to existed table

Revision ID: 772a9961da32
Revises: cf24e6297385
Create Date: 2024-11-24 03:28:30.124222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772a9961da32'
down_revision: Union[str, None] = 'cf24e6297385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_tasks_id'), 'failed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_failed_tasks_url'), 'failed_tasks', ['url'], unique=False)

    op.add_column('completed_tasks', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('retry_counter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE completed_tasks SET create_date = complete_date"
        )
    )
    op.alter_column('completed_tasks', 'create_date', nullable=False, existing_type=sa.DateTime())
    op.alter_column('completed_tasks', 'url', nullable=False, existing_type=sa.Text())
    op.alter_column('tasks', 'url', nullable=False, existing_type=sa.Text())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'retry_counter')
    op.drop_column('completed_tasks', 'create_date')
    op.drop_index(op.f('ix_failed_tasks_url'), table_name='failed_tasks')
    op.drop_index(op.f('ix_failed_tasks_id'), table_name='failed_tasks')
    op.drop_table('failed_tasks')
    # ### end Alembic commands ###
