"""Initial

Revision ID: 90a999ee7c68
Revises: 
Create Date: 2024-09-01 02:22:55.729129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a999ee7c68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('complete_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_tasks_id'), 'completed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_completed_tasks_url'), 'completed_tasks', ['url'], unique=False)
    op.create_table('process_lock',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('acquire_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_process_lock_name'), 'process_lock', ['name'], unique=True)
    op.create_index(op.f('ix_process_lock_pid'), 'process_lock', ['pid'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('retry_after', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_process_lock_pid'), table_name='process_lock')
    op.drop_index(op.f('ix_process_lock_name'), table_name='process_lock')
    op.drop_table('process_lock')
    op.drop_index(op.f('ix_completed_tasks_url'), table_name='completed_tasks')
    op.drop_index(op.f('ix_completed_tasks_id'), table_name='completed_tasks')
    op.drop_table('completed_tasks')
    # ### end Alembic commands ###
