"""add tag field to tasks, completed_tasks and failed_tasks

Revision ID: a1f4c8e2b9d3
Revises: 681e591e93b1
Create Date: 2026-08-21 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f4c8e2b9d3'
down_revision: Union[str, None] = '681e591e93b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tag', sa.String(length=128), nullable=True))
    op.add_column('completed_tasks', sa.Column('tag', sa.String(length=128), nullable=True))
    op.add_column('failed_tasks', sa.Column('tag', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tag')
    op.drop_column('completed_tasks', 'tag')
    op.drop_column('failed_tasks', 'tag')
    # ### end Alembic commands ###
