"""change file_path fields to JSON

Revision ID: c3f6a8d1e5b7
Revises: a1f4c8e2b9d3
Create Date: 2026-08-21 13:00:00.000000

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'c3f6a8d1e5b7'
down_revision: Union[str, None] = 'a1f4c8e2b9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _convert_file_path_value(raw) -> list:
    """Convert a legacy file_path value into a list of {path, skipped} entries."""
    value = raw
    try:
        value = json.loads(raw)
    except (TypeError, ValueError):
        pass  # legacy plain string path

    entries = []
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                entries.append(item)  # already new-style
            else:
                entries.append({"path": item, "skipped": False})
    elif isinstance(value, str) and value:
        entries.append({"path": value, "skipped": False})
    return entries


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # Convert legacy file_path values into JSON arrays of {path, skipped} objects
    for table in ("tasks", "completed_tasks"):
        rows = conn.execute(sa.text(
            f"SELECT id, file_path FROM {table} WHERE file_path IS NOT NULL"
        )).fetchall()
        for row_id, raw in rows:
            entries = _convert_file_path_value(raw)
            conn.execute(
                sa.text(f"UPDATE {table} SET file_path = :fp WHERE id = :id"),
                {"fp": json.dumps(entries), "id": row_id},
            )
    op.alter_column('completed_tasks', 'file_path',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               nullable=True)
    op.alter_column('tasks', 'file_path',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'file_path',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True,
               nullable=True)
    op.alter_column('completed_tasks', 'file_path',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True,
               nullable=True)
    # ### end Alembic commands ###
