"""Add checked to CompletedTask

Revision ID: cf24e6297385
Revises: 90a999ee7c68
Create Date: 2024-11-19 23:55:50.461125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf24e6297385'
down_revision: Union[str, None] = '90a999ee7c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_tasks', sa.Column('checked', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_tasks', 'checked')
    # ### end Alembic commands ###
