"""add task_metadata to completed_tasks

Revision ID: d4e7b9f2c5a8
Revises: c3f6a8d1e5b7
Create Date: 2026-08-21 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e7b9f2c5a8'
down_revision: Union[str, None] = 'c3f6a8d1e5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_tasks', sa.Column('task_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_tasks', 'task_metadata')
    # ### end Alembic commands ###
